[STR_SPRITES_COMPLETE]
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_SPRITES_INCOMPLETE]
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_POWER_SOURCE_BATTERY_HYBRID]
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_POWER_SOURCE_DC]
suppressed_rosters = ["pony", "moose"]

[STR_POWER_SOURCE_METRO]
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_POWER_SOURCE_STEAM]
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_NAME_SUFFIX_ELECTRIC_DC]
suppressed_rosters = ["pony", "moose"]

[STR_NAME_SUFFIX_ELECTRIC_AC_DC]
suppressed_rosters = ["pony", "moose"]

[STR_RAILTYPE_NARROW_GAUGE_ELECTRIFIED_NAME]
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_RAILTYPE_NARROW_GAUGE_ELECTRIFIED_TOOLBAR_CAPTION]
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_RAILTYPE_NARROW_GAUGE_ELECTRIFIED_MENU_TEXT]
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_RAILTYPE_NARROW_GAUGE_ELECTRIFIED_BUILD_WINDOW_CAPTION]
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_RAILTYPE_NARROW_GAUGE_ELECTRIFIED_AUTOREPLACE_TEXT]
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_RAILTYPE_NARROW_GAUGE_ELECTRIFIED_NEW_ENGINE_TEXT]
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_RAILTYPE_RAIL_ELECTRIFIED_AC_DC_NAME]
suppressed_rosters = ["pony", "moose"]

[STR_RAILTYPE_RAIL_ELECTRIFIED_AC_DC_TOOLBAR_CAPTION]
suppressed_rosters = ["pony", "moose"]

[STR_RAILTYPE_RAIL_ELECTRIFIED_AC_DC_MENU_TEXT]
suppressed_rosters = ["pony", "moose"]

[STR_RAILTYPE_RAIL_ELECTRIFIED_AC_DC_BUILD_WINDOW_CAPTION]
suppressed_rosters = ["pony", "moose"]

[STR_RAILTYPE_RAIL_ELECTRIFIED_AC_DC_AUTOREPLACE_TEXT]
suppressed_rosters = ["pony", "moose"]

[STR_RAILTYPE_RAIL_ELECTRIFIED_AC_DC_NEW_ENGINE_TEXT]
suppressed_rosters = ["pony", "moose"]

[STR_RAILTYPE_RAIL_ELECTRIFIED_DC_NAME]
suppressed_rosters = ["pony", "moose"]

[STR_RAILTYPE_RAIL_ELECTRIFIED_DC_TOOLBAR_CAPTION]
suppressed_rosters = ["pony", "moose"]

[STR_RAILTYPE_RAIL_ELECTRIFIED_DC_MENU_TEXT]
suppressed_rosters = ["pony", "moose"]

[STR_RAILTYPE_RAIL_ELECTRIFIED_DC_BUILD_WINDOW_CAPTION]
suppressed_rosters = ["pony", "moose"]

[STR_RAILTYPE_RAIL_ELECTRIFIED_DC_AUTOREPLACE_TEXT]
suppressed_rosters = ["pony", "moose"]

[STR_RAILTYPE_RAIL_ELECTRIFIED_DC_NEW_ENGINE_TEXT]
suppressed_rosters = ["pony", "moose"]

[STR_BUY_MENU_ADDITIONAL_TEXT_HINT_LGV_CAPABLE]
suppressed_rosters = ["pony", "ibex", "moose"]
