[STR_SPRITES_COMPLETE]
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_SPRITES_INCOMPLETE]
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_POWER_SOURCE_BATTERY_HYBRID]
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_POWER_SOURCE_DC]
suppressed_rosters = ["pony", "moose"]

[STR_POWER_SOURCE_METRO]
suppressed_rosters = ["pony", "ibex", "moose"]

[STR_POWER_SOURCE_STEAM]
suppressed_rosters = ["pony", "ibex", "moose"]
